# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12b535a05b0b8cf07fbe745e0ec934929da777b1aebc355c1e372fc384608da91f4a03668de7105dc82a4c233b7b5b2017e17d577dda502c3d7094ec19710f1a

test:
  secret_key_base: 47414b9897fb2cfe28321184419215f15d2ceb264df8da21001ce2ac8b7781b3985003315b738297503d1bfd5f8b866f7b1db1286a45cc62df9302251b7c3ee8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
